name: Generate a build and push to another branch

on:
  push:
    branches:
      - main # The branch name your are commit the new changes

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: |
          composer install
          echo "Installed all dependencies"

      - name: Clear configuration cache
        run: php artisan config:cache

      - name: Clear route cache
        run: php artisan route:clear

      - name: Clear view cache
        run: php artisan view:clear

      - name: Clear application cache
        run: php artisan optimize:clear
